// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJsq89pgedCZygizUGlN-5L-0FGsnxNb8',
    appId: '1:161556229278:web:583d2de6b17a055051df8f',
    messagingSenderId: '161556229278',
    projectId: 'abastecacomzeca',
    authDomain: 'abastecacomzeca.firebaseapp.com',
    storageBucket: 'abastecacomzeca.firebasestorage.app',
    measurementId: 'G-PZX0Q809TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSNBUxiZrDHf2P5KS7XLO2nQ8qWNlINL8',
    appId: '1:161556229278:android:6af0450e4cc96f2d51df8f',
    messagingSenderId: '161556229278',
    projectId: 'abastecacomzeca',
    storageBucket: 'abastecacomzeca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwvtXNX9vtVkfyIyPpEENGM6X2zssPP48',
    appId: '1:161556229278:ios:b474bbc84191924651df8f',
    messagingSenderId: '161556229278',
    projectId: 'abastecacomzeca',
    storageBucket: 'abastecacomzeca.firebasestorage.app',
    iosBundleId: 'com.abasteca.zeca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwvtXNX9vtVkfyIyPpEENGM6X2zssPP48',
    appId: '1:161556229278:ios:899187ac652d1af951df8f',
    messagingSenderId: '161556229278',
    projectId: 'abastecacomzeca',
    storageBucket: 'abastecacomzeca.firebasestorage.app',
    iosBundleId: 'com.example.zecaApp',
  );
}
